language: node_js
node_js:
- node
- lts/*
cache: yarn
before_install:
- yarn global add greenkeeper-lockfile@1
- yarn global add codecov
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload
after_success:
- codecov
notifications:
  slack:
    secure: pORIjmOHXMpJNnSUntnVbB01wdYXYe2sv9WRftNl87hhP5ox66wGgw7S/VEgqJ8IoQ7/N8ZZdhMIqbeiSgj+VhjLiea8RgyVLWwZp2Gq6Aa/DEe2nXxRDBrWTnnjLE8B3OVC2tOgGnl0FxtzOYN5xVXDkABv3tkHQpD7r2YGdN0b/4/L6qNfVfJLQuwP4LeE09VsHF4saGTIJXImYHkL4vhXCgGISN/8pixScHvrctsY2PmKk0ug987GTwA7RTtpHkXhzJFujLoyAVtzsN2ZHkEXbCIP7zGDy0+heOi2zokicGcKWIKxyLJLHNY6bFgcCwYKs+dHOq6Pt08zKTwR0E6Tx/Hk9Kr9Yk69YjxxjaLIWdx1MOIFVUlOb9Kxgfb8wG9i+NEH1AOMuCwBCmNs5TD0E/oF6gTOyR7zo584Papf7dmjRN9bJXF8PkOmpZS++sk9ID+UgnR3LpiK0VFfmtFW4V38EhIGSgGhCzzoywLUYwG7ssr2DNVLGOvo+mLcXR17aq8hhXHyToh6AuurfYcaIja9UIUjy/GloQoc7xOI1+hkHMxwYTb8j3JzEMpqLNYll/ube2W+7wnRAMlgg4Eb2fNbP0cPyRHpYj5AX74NwKAcaEe51SiJxNwAtts4IGRmNZjWK6WLRJxiw/Myj5J6wGk6FBG6yZTd4tPWBds=
