coverage:
  notify:
    slack:
      default:
        url: "secret:DGSSwQNVUeC/J4UrEiHSdZocuwTAod64PpBHk/ouNO5zgA2rLHztBZ8Mbt8Zos5jKWA6ECOX7E0m3za6aLHnMr1YyhgXb/0YewepIZ1xiU2TGOtKZabPz0yfoWiX7nvpghr2Gpycpvy1j10Lelt1+xhvQHqEOqOPXnWycSfH9t0="
        threshold: 1%
        only_pulls: false
        branches: null
        flags: null
        paths: null
