const schemaValidator = require("../schemaValidator");

const inputSchema = schemaValidator
  .object()
  .required()
  .keys({
    // domain [string:ascii] [mandatory]: a .ro domain
    domain: schemaValidator
      .string()
      .required()
      .RoTLDDomain(),

    // authorization_key [string:alphanum] [mandatory]:
    // the authorization key provided by the registrant.
    authorization_key: schemaValidator.string().required(),

    // c_registrant [string] [mandatory]:
    //  The new registrant contact ID (a registrant must be created before).
    // The registrant contact ID must be unique for each trade.
    c_registrant: schemaValidator.string().required(),

    // domain_period [string] [mandatory]:
    // a number between 1 and 10] which represents the number of years.
    // A year has 365 days and it does not account the leap years.
    domain_period: schemaValidator
      .string()
      .required()
      .integer()
      .min(1)
      .max(10),

    // domain_password[string:ascii][optional]:
    // If not present, a password will be generated by the system.
    // If present, the password must have max length: 40 chars, min.length: 5 chars.
    // Regexp: r"^[a-z0-9\-\.\,\:\;\[\]\{\}\_\+\=\@\#\$\^\*\?\!\|\~]{5,40}$",re.IGNORECASE
    domain_password: schemaValidator
      .string()
      .min(5)
      .max(40)
      .RoTLDPassword()
  });

module.exports = inputSchema;
